### ISSUE TITLE
Error inflating class com.edmodo.rangebar.RangeBar

### ISSUE THREAD

**Issue by locoruiz** [edmodo/range-bar#52]
Greetings everybody,
first of all I want to thank for this great tool.
I am having the following problem:
` android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.edmodo.rangebar.RangeBar.`

I am using it by adding the following line in the gradle file:
`compile 'com.edmodo:rangebar:1.0.0'`

I have the following in the xml file:
`<com.edmodo.rangebar.RangeBar
        android:id="@+id/rangeBar"
        android:layout_marginTop="10dp"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:tickCount="101"
        app:tickHeight="0dp"
        />`
It is inside a LinearLayout.
It used to work before but in my new build it doesn't!
Thanks very much in advanced,
Kind Regards,
Ricardo

**Comment by HuzefaGadi** [comment]
Don't do it from XML do it programatically and it will work.

```
rangeBar.setTickCount(50);
rangeBar.setTickHeight(0);
```

**Comment by locoruiz** [comment]
Thank you for the response!
It worked for me by cloning the project and setting the packages to the same as my project.

**Comment by igorbiscanin** [comment]
@locoruiz Did you maybe find the reason for `InflateException`?

**Comment by locoruiz** [comment]
@igorbiscanin as i said, it was fixed after adding the classes to the project, instead of adding them from gradle

**Comment by Rahulv2492** [comment]
@locoruiz did u import added the rangebar library asa module in ur project
